### ISSUE TITLE
Compatibility with jupyter-server 2.x/Jupyterlab 4.x

### ISSUE THREAD

**Issue by q-wertz** [krassowski/jupyterlab-citation-manager#64]
I tried to use jupyterlab-citation-manager but failed to succeed.

Installed the extension in the jupyterlab extension manager, added an API key refreshed the page/restarted the server but no entries can be found.

When I try to install it using poetry I get the following message
```
Using version ^0.3.2 for jupyterlab-citation-manager

Updating dependencies
Resolving dependencies... (0.1s)

Because no versions of jupyterlab-myst match >2,<2.0.1 || >2.0.1,<3
 and jupyterlab-myst (2.0.0) depends on jupyter-server (>=2.0.1,<3), jupyterlab-myst (>=2,<2.0.1 || >2.0.1,<3) requires jupyter-server (>=2.0.1,<3).
And because jupyterlab-myst (2.0.1) depends on jupyter-server (>=2.0.1,<3), jupyterlab-myst (>=2,<3) requires jupyter-server (>=2.0.1,<3).
Because no versions of jupyterlab-citation-manager match >0.3.2,<0.4.0
 and jupyterlab-citation-manager (0.3.2) depends on jupyter-server (>=1.6,<2), jupyterlab-citation-manager (>=0.3.2,<0.4.0) requires jupyter-server (>=1.6,<2).
Thus, jupyterlab-citation-manager (>=0.3.2,<0.4.0) is incompatible with jupyterlab-myst (>=2,<3).
So, because ads-b simulator depends on both jupyterlab-myst (^2) and jupyterlab-citation-manager (^0.3.2), version solving failed.
```

Does jupyterlab-citation-manager not work with the jupyter-server v2 but the Jupyterlab Extension Manager just ignores the requirements?

Or is the problem that I'm using jupyterlab version 4.0.5 which seems to collide with e.g. 

https://github.com/krassowski/jupyterlab-citation-manager/blob/351f616fe6b8532674729d55bee7f584802d660e/pyproject.toml#L2

https://github.com/krassowski/jupyterlab-citation-manager/blob/351f616fe6b8532674729d55bee7f584802d660e/package.json#L60-L62

?

**Comment by krassowski** [comment]
Correct, this extension needs to be upgraded to JupyterLab 4.0.

**Comment by q-wertz** [comment]
Thanks for clarification :)

**Comment by kwilliamszaf** [comment]
I vote for this issue! This would be great to have fixed.

**Comment by krassowski** [comment]
Thank you all for pushing for this one, I opened https://github.com/krassowski/jupyterlab-citation-manager/issues/64 which does the upgrade but there is some automation issue and I run out of stem for today. Hopefully we can get this to work soon.

**Comment by krassowski** [comment]
[v1.0.0a0](https://github.com/krassowski/jupyterlab-citation-manager/releases/tag/v1.0.0a0) (pre-release) should work well with JupyterLab 4.x. You can install it with:

```
pip install jupyterlab-citation-manager==1.0.0a0
```

Please let me know if it works well, in which case I will release it as a final version

**Comment by krassowski** [comment]
Note: I released another alpha [v1.0.0a1](https://github.com/krassowski/jupyterlab-citation-manager/releases/tag/v1.0.0a1)) after fixing an issue around adding citations and updated the comment above.

**Comment by germannl** [comment]
Thank you for the update, it works well on 4.x for me.

**Comment by krassowski** [comment]
Thanks for getting back to me! [v1.0.0](https://github.com/krassowski/jupyterlab-citation-manager/releases/tag/v1.0.0) is now up on PyPI: https://pypi.org/project/jupyterlab-citation-manager/1.0.0/
