### ISSUE TITLE
Insert reference field stay open without possibility to insert reference

### ISSUE THREAD

**Issue by eliselavy** [krassowski/jupyterlab-citation-manager#76]
By using codespaces / docker extension Jupyter Notebook also

- package correctly installed
- ZOTERO API key inserted
-  Zotero synchronized messsage displayed

No possibility to close the input field / no possibility to query the zotero library
no trace in the logs

<img width="1112" alt="Screenshot 2024-03-25 at 11 26 08" src="https://github.com/krassowski/jupyterlab-citation-manager/assets/35602279/6a68a6d3-1fc7-43b7-9792-441db9bdddfa">

Browser: chrome

**Comment by krassowski** [comment]
What does pressing <kbd>Esc</kbd> do?

**Comment by eliselavy** [comment]
> What does pressing Esc do?

indeed it closed the **insert reference** field
but still no access to my zotero library

pressing on the synchronize zotero
do nothing
<img width="294" alt="Screenshot 2024-03-25 at 12 36 03" src="https://github.com/krassowski/jupyterlab-citation-manager/assets/35602279/ab6a34a5-39d6-4b47-bf22-071dda1e5f29">

I manage to use the plugin in codespaces but sometimes this problem occurs 
> low connection?

just maybe feedback needs to be provided

**Comment by krassowski** [comment]
If you open the web developer console (https://webmasters.stackexchange.com/a/77337) at time when it fails to load, are there any logs/errors coming from this extension?

**Comment by eliselavy** [comment]
> If you open the web developer console (https://webmasters.stackexchange.com/a/77337) at time when it fails to load, are there any logs/errors coming from this extension?

Here is an extract from the JupyterLab console:
```
[I 2024-03-26 12:58:57.137 ServerApp] Located 10124 CSL styles for Citation Manager.
[I 2024-03-26 12:58:58.610 ServerApp] Registered jupyterlab_citation_manager extension at URL path /citation-manager
[I 2024-03-26 12:58:58.610 ServerApp] jupyterlab_citation_manager | extension was successfully loaded.
```

Here is an extract of the Chrome console:
[launch_jupyterlab.log](https://github.com/krassowski/jupyterlab-citation-manager/files/14758885/launch_jupyterlab.log)

   Failed to load resource: the server responded with a status of 403 ()
> call https://api.zotero.org/keys/cf92f1678e0efd5cb205546cc75e0a55f1545ec62ead9ddc?
Key 'cf92f1678e0efd5cb205546cc75e0a55f1545ec62ead9ddc' not found

but i used this key in the past.


33.2b66053eaff0db65ac34.js?v=2b66053eaff0db65ac34:1 No previous state found for Zotero in the StateDB (it is normal on first run)
lab:1 Uncaught (in promise) SyntaxError: Unexpected token 'I', "Invalid key" is not valid JSON
lab:1 Uncaught (in promise) SyntaxError: Unexpected token 'I', "Invalid key" is not valid JSON

i conduct a workshop with some users, and i reproduce it , it means wrong copy/paste of the key?

**Comment by eliselavy** [comment]
@krassowski can be closed  maybe, seems related to wrong API key used
